let D=[],target=null,guesses=[],hints=0;
const $=x=>document.getElementById(x);
fetch('data.json').then(r=>r.json()).then(x=>{D=x;fillNames();filters();directory();start('free')});
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');if(id==='stats')stats();if(id==='directory')directory()}
function start(mode){target=mode==='daily'?D[Math.abs(day())%D.length]:D[Math.floor(Math.random()*D.length)];guesses=[];hints=0;$('mode').textContent=mode==='daily'?'DAILY CHALLENGE':'FREE PLAY';$('attempt').textContent=0;$('guess').value='';renderHints();history();go('game')}
function day(){let a=new Date(),b=new Date(2026,0,1);return Math.floor((new Date(a.getFullYear(),a.getMonth(),a.getDate())-b)/86400000)}
function fillNames(){$('names').innerHTML=D.map(x=>`<option value="${x.name}">`).join('')}
function renderHints(){let f=[['성별','gender'],['소속 크루','crew'],['방송 시작','start'],['나이','age'],['애청자 수','fans']];$('hints').innerHTML=f.map((x,i)=>`<div class="hint ${i<hints?'':'locked'}"><small>${x[0]}</small><b>${i<hints?fmt(x[1],target[x[1]]):'???'}</b></div>`).join('')}
function fmt(k,v){return k==='fans'?Number(v).toLocaleString()+'명':k==='age'?v+'세':v}
function hint(){if(hints<5){hints++;renderHints()}else alert('모든 힌트를 공개했습니다.')}
function submitGuess(){let v=$('guess').value.trim(),p=D.find(x=>x.name.toLowerCase()===v.toLowerCase());$('err').textContent='';if(!v)return $('err').textContent='이름을 입력해주세요.';if(!p)return $('err').textContent='도감에 등록된 이름을 입력해주세요.';if(guesses.some(x=>x.id===p.id))return $('err').textContent='이미 입력한 인물입니다.';let c={id:p.id,name:p.name,gender:p.gender===target.gender,crew:p.crew===target.crew,start:p.start===target.start,age:p.age===target.age,fans:p.fans===target.fans};guesses.push(c);$('attempt').textContent=guesses.length;$('guess').value='';history();if(p.id===target.id)finish(true)}
function history(){ $('count').textContent=guesses.length+'회';if(!guesses.length)return $('history').className='empty',$('history').textContent='아직 입력한 답이 없습니다.';$('history').className='';$('history').innerHTML=guesses.slice().reverse().map(g=>`<div class="history-row"><b>${g.name}</b><span class="${g.gender?'yes':'no'}">${g.gender?'✓':'✕'} 성별</span><span class="${g.crew?'yes':'no'}">${g.crew?'✓':'✕'} 소속</span><span class="${g.start?'yes':'near'}">${g.start?'✓':'↕'} 시작</span><span class="${g.age?'yes':'near'}">${g.age?'✓':'↕'} 나이</span><span class="${g.fans?'yes':'near'}">${g.fans?'✓':'↕'} 팬</span></div>`).join('')}
function answer(){finish(false)}
function finish(win){let s=JSON.parse(localStorage.whoStats||'{"p":0,"w":0,"a":[]}');s.p++;if(win)s.w++;s.a.push(guesses.length);localStorage.whoStats=JSON.stringify(s);$('modalText').innerHTML=win?`<h2>🎉 정답입니다!</h2><div class="answer">${target.name}</div><p>${guesses.length}번 만에 맞혔습니다.</p>`:`<h2>🏳️ 정답 공개</h2><div class="answer">${target.name}</div><p>다음에는 더 적은 시도로 도전해보세요.</p>`;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function stats(){let s=JSON.parse(localStorage.whoStats||'{"p":0,"w":0,"a":[]}');$('played').textContent=s.p;$('wins').textContent=s.w;$('rate').textContent=s.p?Math.round(s.w/s.p*100)+'%':'0%';$('avg').textContent=s.a.length?(s.a.reduce((a,b)=>a+b,0)/s.a.length).toFixed(1):0}
function filters(){let add=(id,k)=>[...new Set(D.map(x=>x[k]))].sort().forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option>${v}</option>`));add('gender','gender');add('crew','crew')}
function directory(){let q=($('search')?.value||'').toLowerCase(),g=$('gender')?.value||'',c=$('crew')?.value||'';let a=D.filter(x=>(!q||x.name.toLowerCase().includes(q))&&(!g||x.gender===g)&&(!c||x.crew===c));$('rows').innerHTML=a.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.gender}</td><td>${x.crew}</td><td>${x.start}</td><td>${x.age}세</td><td>${Number(x.fans).toLocaleString()}</td></tr>`).join('')}
function resetFilters(){$('search').value='';$('gender').value='';$('crew').value='';directory()}
$('guess').addEventListener('keydown',e=>{if(e.key==='Enter')submitGuess()});$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('search').addEventListener('input',directory);$('gender').addEventListener('change',directory);$('crew').addEventListener('change',directory);
