const DEFAULT_DATA=[
  {"id":1,"name":"유명한 노래 1초 듣고 맞히기","category":"노래","type":"맞히기","date":"2026-01-26","format":"단독","url":"https://www.sooplive.com/station/bbungchi","thumbnail":""},
  {"id":2,"name":"파스파트2","category":"게임","type":"경영·시뮬레이션","date":"2026-01-25","format":"단독","url":"https://vod.sooplive.com/player/184893207","thumbnail":"https://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=184893207&column=thum"},
  {"id":3,"name":"릴리의 우물","category":"게임","type":"공포","date":"2026-01-23","format":"단독","url":"https://vod.sooplive.com/player/184679953","thumbnail":"https://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=184679953&column=thum"},
  {"id":4,"name":"에겐력 컨설팅","category":"토크","type":"컨설팅","date":"2026-01-22","format":"합방","url":"https://vod.sooplive.com/player/184564093","thumbnail":"https://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=184564093&column=thum"},
  {"id":5,"name":"PEAK","category":"게임","type":"협동","date":"2026-01-15","format":"합방","url":"https://vod.sooplive.com/player/183795783","thumbnail":"https://videoimg.afreecatv.com/php/SnapshotLoad.php?rowKey=183795783&column=thum"},
  {"id":6,"name":"화장실 사유 월드컵","category":"월드컵","type":"이상형 월드컵","date":"2026-01-14","format":"단독","url":"https://www.sooplive.com/station/bbungchi/post/183708015","thumbnail":""},
  {"id":7,"name":"산나비","category":"게임","type":"액션·어드벤처","date":"2025-10-11","format":"단독","url":"https://www.sooplive.com/station/bbungchi/post/174489097","thumbnail":""},
  {"id":8,"name":"KITTY KART 64","category":"게임","type":"공포·레이싱","date":"날짜 미확인","format":"단독","url":"https://www.sooplive.com/station/bbungchi","thumbnail":""}
];
let D=[],target=null,guesses=[],hints=0;
const $=x=>document.getElementById(x);
function init(x){D=Array.isArray(x)&&x.length?x:DEFAULT_DATA;fillNames();filters();directory()}
fetch('data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(init).catch(()=>init(DEFAULT_DATA));
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');if(id==='stats')stats();if(id==='directory')directory()}
function start(mode){target=mode==='daily'?D[Math.abs(day())%D.length]:D[Math.floor(Math.random()*D.length)];guesses=[];hints=0;$('mode').textContent=mode==='daily'?'DAILY CHALLENGE':'FREE PLAY';$('attempt').textContent=0;$('guess').value='';renderHints();history();go('game')}
function day(){let a=new Date(),b=new Date(2026,0,1);return Math.floor((new Date(a.getFullYear(),a.getMonth(),a.getDate())-b)/86400000)}
function fillNames(){$('names').innerHTML=D.map(x=>`<option value="${x.name}">`).join('')}
function renderHints(){let f=[['콘텐츠','category'],['구분','type'],['방송일','date'],['진행 형태','format']];$('hints').innerHTML=f.map((x,i)=>`<div class="hint ${i<hints?'':'locked'}"><small>${x[0]}</small><b>${i<hints?target[x[1]]:'???'}</b></div>`).join('')}
function hint(){if(hints<4){hints++;renderHints()}else alert('모든 힌트를 공개했습니다.')}
function submitGuess(){let v=$('guess').value.trim(),p=D.find(x=>x.name.toLowerCase()===v.toLowerCase());$('err').textContent='';if(!v)return $('err').textContent='콘텐츠 이름을 입력해주세요.';if(!p)return $('err').textContent='도감에 등록된 콘텐츠를 입력해주세요.';if(guesses.some(x=>x.id===p.id))return $('err').textContent='이미 입력한 콘텐츠입니다.';let c={id:p.id,name:p.name,category:p.category===target.category,type:p.type===target.type,date:p.date===target.date,format:p.format===target.format};guesses.push(c);$('attempt').textContent=guesses.length;$('guess').value='';history();if(p.id===target.id)finish(true)}
function history(){ $('count').textContent=guesses.length+'회';if(!guesses.length)return $('history').className='empty',$('history').textContent='아직 입력한 답이 없습니다.';$('history').className='';$('history').innerHTML=guesses.slice().reverse().map(g=>`<div class="history-row"><b>${g.name}</b><span class="${g.category?'yes':'no'}">${g.category?'✓':'✕'} 콘텐츠</span><span class="${g.type?'yes':'no'}">${g.type?'✓':'✕'} 구분</span><span class="${g.date?'yes':'near'}">${g.date?'✓':'↕'} 방송일</span><span class="${g.format?'yes':'no'}">${g.format?'✓':'✕'} 진행 형태</span></div>`).join('')}
function answer(){finish(false)}
function resultMedia(){let fallback=`<div class="result-fallback" style="display:grid">SOOP 연토리뿡치</div>`;let image=target.thumbnail?`<img class="result-thumb" src="${target.thumbnail}" alt="${target.name} SOOP 썸네일" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="result-fallback">SOOP 연토리뿡치</div>`:fallback;return `${image}<a class="soop-link" href="${target.url}" target="_blank" rel="noopener noreferrer">▶ SOOP에서 보기</a><small class="result-url">${target.url}</small>`}
function finish(win){let s=JSON.parse(localStorage.whoStats||'{"p":0,"w":0,"a":[]}');s.p++;if(win)s.w++;s.a.push(guesses.length);localStorage.whoStats=JSON.stringify(s);$('modalText').innerHTML=win?`<h2>🎉 정답입니다!</h2><div class="answer">${target.name}</div><p>${guesses.length}번 만에 맞혔습니다.</p>${resultMedia()}`:`<h2>🏳️ 정답 공개</h2><div class="answer">${target.name}</div><p>다음에는 더 적은 시도로 도전해보세요.</p>${resultMedia()}`;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function stats(){let s=JSON.parse(localStorage.whoStats||'{"p":0,"w":0,"a":[]}');$('played').textContent=s.p;$('wins').textContent=s.w;$('rate').textContent=s.p?Math.round(s.w/s.p*100)+'%':'0%';$('avg').textContent=s.a.length?(s.a.reduce((a,b)=>a+b,0)/s.a.length).toFixed(1):0}
function filters(){let add=(id,k)=>[...new Set(D.map(x=>x[k]))].sort().forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option>${v}</option>`));add('category','category');add('type','type')}
function directory(){let q=($('search')?.value||'').toLowerCase(),g=$('category')?.value||'',c=$('type')?.value||'';let a=D.filter(x=>(!q||x.name.toLowerCase().includes(q))&&(!g||x.category===g)&&(!c||x.type===c));$('directoryCount').textContent=D.length+'개';$('rows').innerHTML=a.length?a.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.category}</td><td>${x.type}</td><td>${x.date}</td><td>${x.format}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">조건에 맞는 콘텐츠가 없습니다.</td></tr>`}
function resetFilters(){$('search').value='';$('category').value='';$('type').value='';directory()}
$('guess').addEventListener('keydown',e=>{if(e.key==='Enter')submitGuess()});$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('search').addEventListener('input',directory);$('category').addEventListener('change',directory);$('type').addEventListener('change',directory);
